spring.application.name=ex02_mybatis

#datasource (oracle) 
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr

#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.example.demo
mybatis.mapper-locations=classpath:mapper/**/*.xml

logging.level.root=info
logging.level.com.example.demo=trace

logging.pattern.console= %-5level %logger{20} - [%L]%msg%n

# message properties(https://github.com/cyannara/springboot/blob/main/springboot03_controller.md - 다국어처리)
spring.messages.basename=message
spring.messages.encoding=UTF-8

file.upload=c:/upload

# trace 포함 여부(on-param -> ?trace해야 나옴)
server.error.include-stacktrace=on-param  