spring.application.name=exam

#datasource (oracle) 
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr

#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.exam
mybatis.mapper-locations=classpath:mapper/**/*.xml

logging.level.root=info
logging.level.com.example.demo=trace

logging.pattern.console= %-5level %logger{20} - [%L]%msg%n

#환경변수(파일업로드시)
file.upload=D:/Dev/workspace/exam/src/main/resources/static/images